### ISSUE TITLE
There isnt sql tables

### ISSUE THREAD

**Issue by jona950** [panyifei/nodejs-restaurant#1]
when i try to log in, node giving me a error:
at Error (native)
    at IncomingMessage._flash [as flash](D:restaurantnode_modulesconnect-flashlibflash.js:60:41)
    at allFailed (D:\restaurant\node_modules\passport\lib\middleware\authenticate.js:111:15)
    at attempt (D:\restaurant\node_modules\passport\lib\middleware\authenticate.js:160:28)
    at Strategy.strategy.fail (D:\restaurant\node_modules\passport\lib\middleware\authenticate.js:277:9)
    at verified (D:\restaurant\node_modules\passport-local\lib\strategy.js:82:30)
    at D:\restaurant\util\passport-init.js:14:20
    at Runner_MySQL.<anonymous> (D:\restaurant\service\user.js:32:28)
    at Runner_MySQL.tryCatcher (D:\restaurant\node_modules\bluebird\js\main\util.js:26:23)
    at Promise.successAdapter (D:\restaurant\node_modules\bluebird\js\main\nodeify.js:23:30)
    at Promise._settlePromiseAt (D:\restaurant\node_modules\bluebird\js\main\promise.js:579:21)
    at Promise._settlePromises (D:\restaurant\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (D:\restaurant\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\restaurant\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](D:restaurantnode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by jona950** [comment]
could you provide me the tables of your project?

**Comment by wero1414** [comment]
me too pls
